### PR TITLE
Adding Avalonia sample

### LINKED ISSUE #82: Avalonia UI base sample
Do the TodoApp for Avalonia UI

### PR DESCRIPTION
**Pull request by timunie**
Any Feedback is welcome. 

This is how Deskop looks like: 
image

Targets tested:

**Desktop**:
- [x] Windows
- [ ] MacOS
- [ ] Linux

**Mobile**:
- [x] Android 
- [ ] iOS

**WASM**:
- [x] Browser

> [!NOTE]
> I don't have the option to test the other build targes. But if anyone wants to try, that would be appreciated. 

Fixes #82

### CODE REVIEW

**Comment by adrianhall** [comment]
I'll validate this tomorrow.  In the interim, it would be good to also submit a walk through to the docs in the same style as the other sample walk throughs.

**Comment by timunie** [comment]
Hi @adrianhall 

Do you happen to know why I got the stale label applied? If anything is missing for review, please let me know. 

Otherwise will wait patiently. Thank you.

**Comment by adrianhall** [comment]
The stale processing is automatic through a GitHub action.  I’ve been swamped at work, so will look at this - hopefully today.

**Comment by timunie** [comment]
All fine from my side. I totally understand how challenging OSS can be. Feel free to postpone your review and enjoy your weekend instead 🙂

**Comment by adrianhall** [comment]
Downloaded the PR and went to the TodoApp.Avalonia.sln to test.

- The CommunityToolkit.Datasync.Client.csproj could not be found.
- EF Core and associated NuGets could not be restored.

While I can see what is wrong, I suggest you update the project files on your branch and use the NuGet package rather than the project reference so that it can be properly tested.

**Comment by timunie** [comment]
Updated to use nuget packages instead. Hope this helps. Runs fine on my end.

**Comment by adrianhall** [comment]
Comments from todays run through. 

For this one, I opened samples/todoapp/Sample.TodoApp.sln

1. LoggingHandler was not found after uncommenting the relevant code.  Please add LoggingHandler into your Services directory (it can be a direct copy from the WinUI3 one)
2. I have a datasync-server running - you have obviously changed yours.  Here is the error:

```text
[HTTP] <<< BadRequest Bad Request
[HTTP] >>> [{"memberNames":["Title"],"errorMessage":"The Title field is required."}]
[HTTP] >>> POST https://app-h2qwg7ctqmor2.azurewebsites.net/tables/todoitem
[HTTP] >>> {"content":"Learn Avalonia","id":"634818ec95ac4869a2e9cee0e75ab326"}
[HTTP] <<< BadRequest Bad Request
[HTTP] >>> [{"memberNames":["Title"],"errorMessage":"The Title field is required."}]
```

The code looks good, basically.  We just need to tighten it up.  I recommend that you switch to a new blank directory and checkout the code anew; deploy the datasync-server; then go through exactly what you would go through for the tutorial.  It shows up these errors rather easily.

**Comment by timunie** [comment]
Hey @adrianhall ,

could the error be that I renamed Title to Content in the ToDoItem?

**Review by adrianhall — APPROVED** [review]

**Pull request merged**
